### ISSUE TITLE
thread 'main' panicked error at execution

### ISSUE THREAD

**Issue by notklaatu** [alexpdp7/cmdainer#233]
I'm on Fedora Silverblue 38, attempting to use `cmdainer` for flamel.

After navigating to a course dir, into `guides`, I execute `flamel sg` and get this error:

```
$ flamel sg
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:180:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$ RUST_BACKTRACE=1 flamel sg
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:180:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am not in any toolbox environment.

**Comment by alexpdp7** [comment]
This sounds like you don't have neither `podman` nor `docker` in your path. Do I know you? My GitHub account has my real name, so you can locate me in our employer's Google Chat (or Slack) and we can troubleshoot).

(That'd be tomorrow, because it's getting late here. But now I'm actually intrigued...)

**Comment by notklaatu** [comment]
Podman is in my "normal" path but maybe I'm missing a subtly of either Silverblue or containers.

Here's proof:

```
$ flamel
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:180:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
1015 [moloch 10.0.1.172] [/var/home/skenlon/Documents/RH104/guides] [ workspace-seth][🐍 3.11.4] [☕ ]
$ which podman
/usr/bin/podman
```

I'm in New Zealand, but I'll contact you at work tomorrow, thanks.

**Comment by alexpdp7** [comment]
After some debugging, it seems that [the which library](https://github.com/harryfei/which-rs/) is failing to find `podman` in the path, [here](https://github.com/alexpdp7/cmdainer/blob/master/src/main.rs#L143) and [here](https://github.com/alexpdp7/cmdainer/blob/master/src/main.rs#L184), and thus `cmdainer` is trying to execute `docker` instead of `podman`. As `docker` is not available either, this fails.
